alias dc="docker-compose"
alias dcu="docker-compose up -d"
alias dcps="docker-compose ps"
alias dcpsw="watch -n 5 docker-compose ps"
alias dcurecreate="docker-compose up -d --force-recreate"
alias dcd="docker-compose down"
alias dckill="docker-compose rm --force --stop"
