alias dc="docker-compose"
alias dcu="dc up -d"
alias dcps="dc ps"
alias dcpsw="watch -n 5 docker-compose ps"
alias dcurecreate="dc up -d --force-recreate"
alias dcd="dc down"
alias dckill="dc rm --force --stop"
